<?php

// Android XML Views resources (DEC-047, 43 §13), included by tools/gen-design.
// Every value comes from design/tokens.json; layouts and Kotlin only reference these resources.

declare(strict_types=1);

$res = 'androidapp/core/design/src/main/res';

/** camelCase token keys become snake_case resource names: onPrimary → on_primary. */
function tokenResName(string $key): string
{
    return androidName((string) preg_replace('/(?<=[a-z0-9])([A-Z])/', '_$1', $key));
}

$header = '<!-- Generated by tools/gen-design. Do not edit. -->';
$android = 'xmlns:android="http://schemas.android.com/apk/res/android"';

$color = static function (string $token) use ($tokens): string {
    if (! isset($tokens['color'][$token])) {
        throw new RuntimeException("Unknown color token {$token}");
    }

    return '@color/bremo_'.tokenResName($token);
};
$dimen = static fn (string $group, string $name): string => '@dimen/bremo_'.$group.'_'.tokenResName($name);

// ── dimens.xml ──────────────────────────────────────────────────────────
$dimens = ['<?xml version="1.0" encoding="utf-8"?>', $header, '<resources>'];
foreach (['space', 'radius'] as $group) {
    foreach ($tokens[$group] as $name => $value) {
        $dimens[] = '    <dimen name="bremo_'.$group.'_'.tokenResName((string) $name).'">'.num($value).'dp</dimen>';
    }
}
$integers = [];
foreach ($tokens['size'] as $name => $value) {
    $entries = is_array($value) ? $value : ['' => $value];
    foreach ($entries as $axis => $entryValue) {
        $entryName = tokenResName((string) $name.($axis === '' ? '' : ucfirst((string) $axis)));
        if ($axis === 'columns') {
            $integers[] = '    <integer name="bremo_size_'.$entryName.'">'.$entryValue.'</integer>';

            continue;
        }
        $dimens[] = '    <dimen name="bremo_size_'.$entryName.'">'.num($entryValue).'dp</dimen>';
    }
}
$dimens[] = '    <dimen name="bremo_border_width">'.num($tokens['border']['width']).'dp</dimen>';
$dimens[] = '    <dimen name="bremo_border_selected_width">'.num($tokens['border']['selectedWidth']).'dp</dimen>';
$dimens[] = '    <dimen name="bremo_icon_stroke">'.num($tokens['icon']['stroke']).'dp</dimen>';
foreach ($tokens['type'] as $name => $value) {
    $dimens[] = '    <dimen name="bremo_text_'.tokenResName((string) $name).'">'.num($value['size']).'sp</dimen>';
}
$dimens[] = '</resources>';
syncText($root, $res.'/values/dimens.xml', implode("\n", $dimens)."\n", $checkOnly, $errors, $outputs);

// ── Non-dimensional values: opacity, ratios, thresholds, columns, motion ─
$values = ['<?xml version="1.0" encoding="utf-8"?>', $header, '<resources>'];
$values[] = '    <item name="bremo_opacity_disabled" format="float" type="dimen">'.num($tokens['opacity']['disabled']).'</item>';
foreach ($tokens['ratio'] as $name => $value) {
    $values[] = '    <item name="bremo_ratio_'.tokenResName((string) $name).'" format="float" type="dimen">'.num($value).'</item>';
}
$values[] = '    <item name="bremo_a11y_max_font_scale" format="float" type="dimen">'.num($tokens['a11y']['maxFontScale']).'</item>';
foreach ($tokens['threshold'] as $name => $value) {
    $values[] = '    <integer name="bremo_threshold_'.tokenResName((string) $name).'">'.$value.'</integer>';
}
foreach ($tokens['motion'] as $name => $value) {
    $values[] = '    <integer name="bremo_motion_'.tokenResName((string) $name).'">'.$value.'</integer>';
}
array_push($values, ...$integers);
// DEC-063: shadow tokens as elevations (half the blur), coloured by bremo_shadow_*.
foreach ($tokens['shadow'] as $name => $shadow) {
    $values[] = '    <dimen name="bremo_elevation_'.tokenResName((string) $name).'">'.num($shadow['blur'] / 2).'dp</dimen>';
}
// Scrim alpha for the bottom-sheet dialog comes from the scrim colour token.
$scrimAlpha = hexdec(substr(argb(colorHex($tokens['color']['scrim'])), 0, 2)) / 255;
$values[] = '    <item name="bremo_opacity_scrim" format="float" type="dimen">'.num(round($scrimAlpha, 2)).'</item>';
$values[] = '</resources>';
syncText($root, $res.'/values/bremo_values.xml', implode("\n", $values)."\n", $checkOnly, $errors, $outputs);

// ── font/cairo.xml: one family, one static file per weight (43 §2) ──────
$fontFamily = ['<?xml version="1.0" encoding="utf-8"?>', $header, '<font-family '.$android.' xmlns:app="http://schemas.android.com/apk/res-auto">'];
foreach ($tokens['font']['files'] as $weightKey => $file) {
    $weight = $tokens['font']['weights'][$weightKey];
    $fontName = androidName($file);
    $fontFamily[] = "    <font android:font=\"@font/{$fontName}\" android:fontStyle=\"normal\" android:fontWeight=\"{$weight}\" app:font=\"@font/{$fontName}\" app:fontStyle=\"normal\" app:fontWeight=\"{$weight}\" />";
}
$fontFamily[] = '</font-family>';
$familyName = androidName($tokens['font']['family']);
syncText($root, $res.'/font/'.$familyName.'.xml', implode("\n", $fontFamily)."\n", $checkOnly, $errors, $outputs);
$fontFor = static fn (string $weightKey): string => '@font/'.androidName($tokens['font']['files'][$weightKey]);

// ── Color state lists (res/color) ───────────────────────────────────────
$stateLists = [
    // [states => color] in priority order; the last entry is the default.
    'bremo_button_primary_bg' => [['android:state_pressed="true"', 'primary700'], ['', 'primary600']],
    'bremo_selectable_fill' => [['android:state_checked="true"', $tokens['border']['selectedFill']], ['android:state_selected="true"', $tokens['border']['selectedFill']], ['', 'surface']],
    'bremo_selectable_stroke' => [['android:state_checked="true"', $tokens['border']['selectedColor']], ['android:state_selected="true"', $tokens['border']['selectedColor']], ['', 'border']],
    'bremo_nav_item' => [['android:state_checked="true"', 'primary500'], ['', 'slate400']],
    'bremo_field_stroke' => [['android:state_focused="true"', 'primary600'], ['', 'border']],
];
foreach ($stateLists as $name => $items) {
    $xmlItems = array_map(
        static fn (array $item): string => '    <item '.($item[0] === '' ? '' : $item[0].' ').'android:color="'.$color($item[1]).'" />',
        $items,
    );
    syncText($root, $res.'/color/'.$name.'.xml', implode("\n", ['<?xml version="1.0" encoding="utf-8"?>', $header, '<selector '.$android.'>', ...$xmlItems, '</selector>'])."\n", $checkOnly, $errors, $outputs);
}

// ── Shape drawables ─────────────────────────────────────────────────────
/**
 * @param  array{shape?: string, fill?: string, stroke?: string, strokeWidth?: string, radius?: string, topRadius?: string}  $spec
 */
$shapeBody = static function (array $spec, string $indent) use ($color, $tokens): string {
    $lines = [];
    if (isset($spec['gradient'])) {
        // DEC-063: top-start to bottom-end (315°), or top to bottom (270°) for screen backdrops.
        if (! isset($tokens['gradient'][$spec['gradient']])) {
            throw new RuntimeException("Unknown gradient token {$spec['gradient']}");
        }
        $gradientName = 'bremo_gradient_'.tokenResName($spec['gradient']);
        $lines[] = $indent.'    <gradient android:type="linear" android:angle="'.($spec['angle'] ?? 315).'" android:startColor="@color/'.$gradientName.'_from" android:endColor="@color/'.$gradientName.'_to" />';
    }
    if (isset($spec['fill'])) {
        $lines[] = $indent.'    <solid android:color="'.$color($spec['fill']).'" />';
    }
    if (isset($spec['stroke'])) {
        $lines[] = $indent.'    <stroke android:width="'.$spec['strokeWidth'].'" android:color="'.$color($spec['stroke']).'" />';
    }
    if (isset($spec['radius'])) {
        $lines[] = $indent.'    <corners android:radius="'.$spec['radius'].'" />';
    }
    if (isset($spec['topRadius'])) {
        $lines[] = $indent.'    <corners android:topLeftRadius="'.$spec['topRadius'].'" android:topRightRadius="'.$spec['topRadius'].'" android:bottomLeftRadius="0dp" android:bottomRightRadius="0dp" />';
    }

    return $indent.'<shape android:shape="'.($spec['shape'] ?? 'rectangle').'">'."\n".implode("\n", $lines)."\n".$indent.'</shape>';
};

$border = '@dimen/bremo_border_width';
$selectedBorder = '@dimen/bremo_border_selected_width';
$control = '@dimen/bremo_size_control_stroke';
$shapes = [
    'bremo_bg_card' => ['fill' => 'surface', 'stroke' => 'border', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'card')],
    'bremo_bg_surface' => ['fill' => 'surface'],
    'bremo_bg_divider' => ['fill' => 'border'],
    'bremo_bg_scrim' => ['fill' => 'scrim'],
    'bremo_bg_field' => ['fill' => 'surface', 'stroke' => 'border', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'field')],
    'bremo_bg_field_focused' => ['fill' => 'surface', 'stroke' => 'primary600', 'strokeWidth' => $selectedBorder, 'radius' => $dimen('radius', 'field')],
    'bremo_bg_field_error' => ['fill' => 'surface', 'stroke' => 'danger', 'strokeWidth' => $selectedBorder, 'radius' => $dimen('radius', 'field')],
    'bremo_bg_currency_box' => ['fill' => 'surfaceAlt2', 'radius' => $dimen('radius', 'badge')],
    'bremo_bg_badge_highlight' => ['fill' => 'badgeBg', 'radius' => $dimen('radius', 'badge')],
    'bremo_bg_badge_status' => ['fill' => 'primary50Available', 'radius' => $dimen('radius', 'badge')],
    'bremo_bg_badge_edit' => ['fill' => 'primary50', 'radius' => $dimen('radius', 'badge')],
    'bremo_bg_tag' => ['fill' => 'surfaceAlt', 'radius' => $dimen('radius', 'badge')],
    'bremo_bg_skeleton_line' => ['fill' => 'surfaceAlt', 'radius' => $dimen('radius', 'badge')],
    'bremo_bg_menu_icon_box' => ['fill' => 'surfaceAlt', 'radius' => $dimen('radius', 'menu_icon_box')],
    'bremo_bg_banner_info' => ['fill' => 'primary50Info', 'radius' => $dimen('radius', 'card')],
    'bremo_bg_banner_warning' => ['fill' => 'warningBg', 'radius' => $dimen('radius', 'card')],
    'bremo_bg_banner_offline' => ['fill' => 'surfaceAlt', 'radius' => $dimen('radius', 'card')],
    'bremo_bg_map_card' => ['fill' => 'surfaceAlt2', 'stroke' => 'border', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'card')],
    'bremo_bg_map_button' => ['fill' => 'surface', 'stroke' => 'border', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'button')],
    'bremo_bg_rating_track' => ['fill' => 'surfaceAlt', 'radius' => $dimen('radius', 'full')],
    'bremo_bg_rating_fill' => ['fill' => 'primary500', 'radius' => $dimen('radius', 'full')],
    'bremo_bg_sheet' => ['fill' => 'surface', 'topRadius' => $dimen('radius', 'sheet_top')],
    'bremo_bg_sheet_handle' => ['fill' => 'border', 'radius' => $dimen('radius', 'full')],
    'bremo_bg_bubble_sent' => ['gradient' => 'brand', 'radius' => $dimen('radius', 'card')],
    'bremo_bg_bubble_received' => ['fill' => 'surface', 'stroke' => 'border', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'card')],
    'bremo_bg_bubble_blocked' => ['fill' => 'surface', 'stroke' => 'danger', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'card')],
    'bremo_bg_check_row' => ['fill' => 'surface', 'stroke' => 'border', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'field')],
    'bremo_bg_check_row_checked' => ['fill' => 'primary50', 'stroke' => 'border', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'field')],
    'bremo_bg_checkbox' => ['fill' => 'surface', 'stroke' => 'slate300', 'strokeWidth' => $control, 'radius' => $dimen('radius', 'checkbox')],
    'bremo_bg_checkbox_checked' => ['gradient' => 'brand', 'radius' => $dimen('radius', 'checkbox')],
    'bremo_bg_radio' => ['shape' => 'oval', 'stroke' => 'slate300', 'strokeWidth' => $control],
    'bremo_bg_radio_checked' => ['shape' => 'oval', 'stroke' => 'primary600', 'strokeWidth' => $control],
    'bremo_bg_avatar' => ['shape' => 'oval', 'fill' => 'surfaceAlt'],
    'bremo_bg_verified_shield' => ['shape' => 'oval', 'fill' => 'primary500', 'stroke' => 'surface', 'strokeWidth' => $control],
    'bremo_bg_status_dot' => ['shape' => 'oval', 'fill' => 'primary500'],
    'bremo_bg_eta_icon' => ['shape' => 'oval', 'fill' => 'primary50Info'],
    'bremo_bg_feedback_empty' => ['shape' => 'oval', 'gradient' => 'iconWell'],
    'bremo_bg_feedback_error' => ['shape' => 'oval', 'fill' => 'surfaceAlt'],
    'bremo_bg_step_filled' => ['shape' => 'oval', 'gradient' => 'brand'],
    'bremo_bg_step_on_hold' => ['shape' => 'oval', 'fill' => 'star', 'stroke' => 'star', 'strokeWidth' => $control],
    'bremo_bg_step_pending' => ['shape' => 'oval', 'fill' => 'surface', 'stroke' => 'border', 'strokeWidth' => $control],
    'bremo_bg_stepper_done' => ['shape' => 'oval', 'gradient' => 'brand'],
    'bremo_bg_stepper_active' => ['shape' => 'oval', 'fill' => 'surface', 'stroke' => 'primary600', 'strokeWidth' => $control],
    'bremo_bg_stepper_on_hold' => ['shape' => 'oval', 'fill' => 'surface', 'stroke' => 'star', 'strokeWidth' => $control],
    'bremo_bg_stepper_pending' => ['shape' => 'oval', 'fill' => 'surface', 'stroke' => 'border', 'strokeWidth' => $control],
    'bremo_dot_primary' => ['shape' => 'oval', 'fill' => 'primary600'],
    // DEC-063 — gradient surfaces.
    'bremo_bg_hero' => ['gradient' => 'hero', 'radius' => $dimen('radius', 'hero_card')],
    'bremo_bg_urgent' => ['gradient' => 'urgent', 'radius' => $dimen('radius', 'card')],
    'bremo_bg_urgent_button' => ['gradient' => 'urgentButton', 'radius' => $dimen('radius', 'button')],
    'bremo_bg_icon_well' => ['gradient' => 'iconWell', 'radius' => $dimen('radius', 'menu_icon_box')],
    'bremo_bg_icon_well_round' => ['shape' => 'oval', 'gradient' => 'iconWell'],
    'bremo_bg_brand_round' => ['shape' => 'oval', 'gradient' => 'iconBrand'],
    'bremo_bg_nav_pill' => ['gradient' => 'iconWell', 'radius' => $dimen('radius', 'full')],
    'bremo_bg_hero_well' => ['fill' => 'onHeroWell', 'radius' => $dimen('radius', 'menu_icon_box')],
    'bremo_bg_icon_well_danger' => ['fill' => 'dangerTint', 'radius' => $dimen('radius', 'menu_icon_box')],
    'bremo_bg_menu_group' => ['fill' => 'surface', 'radius' => $dimen('radius', 'card')],
    'bremo_bg_screen' => ['gradient' => 'screen', 'angle' => 270],
    'bremo_dot_star' => ['shape' => 'oval', 'fill' => 'star'],
];
foreach ($shapes as $name => $spec) {
    $xmlShape = str_replace('<shape ', '<shape '.$android.' ', $shapeBody($spec, ''));
    syncText($root, $res.'/drawable/'.$name.'.xml', '<?xml version="1.0" encoding="utf-8"?>'."\n".$header."\n".$xmlShape."\n", $checkOnly, $errors, $outputs);
}

// Spacing between LinearLayout children (showDividers="middle"): one transparent gap per space token.
foreach ($tokens['space'] as $name => $value) {
    $gapName = 'bremo_gap_'.tokenResName((string) $name);
    $gap = implode("\n", [
        '<?xml version="1.0" encoding="utf-8"?>',
        $header,
        '<shape '.$android.' android:shape="rectangle">',
        '    <solid android:color="@android:color/transparent" />',
        '    <size android:width="@dimen/bremo_space_'.tokenResName((string) $name).'" android:height="@dimen/bremo_space_'.tokenResName((string) $name).'" />',
        '</shape>',
    ]);
    syncText($root, $res.'/drawable/'.$gapName.'.xml', $gap."\n", $checkOnly, $errors, $outputs);
}

// DEC-063: hairline between rows of a menu group.
syncText($root, $res.'/drawable/bremo_divider_line.xml', implode("\n", [
    '<?xml version="1.0" encoding="utf-8"?>',
    $header,
    '<shape '.$android.' android:shape="rectangle">',
    '    <solid android:color="'.$color('border').'" />',
    '    <size android:height="@dimen/bremo_border_width" />',
    '</shape>',
])."\n", $checkOnly, $errors, $outputs);

// Selection frames: the chosen state is a selector (43 §3 "مختار / غير مختار").
$selectors = [
    'bremo_bg_selectable_card' => [
        ['android:state_selected="true"', ['fill' => $tokens['border']['selectedFill'], 'stroke' => $tokens['border']['selectedColor'], 'strokeWidth' => $selectedBorder, 'radius' => $dimen('radius', 'card')]],
        ['', ['fill' => 'surface', 'stroke' => 'border', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'card')]],
    ],
    'bremo_bg_selectable_chip' => [
        ['android:state_selected="true"', ['fill' => $tokens['border']['selectedFill'], 'stroke' => $tokens['border']['selectedColor'], 'strokeWidth' => $selectedBorder, 'radius' => $dimen('radius', 'chip')]],
        ['', ['fill' => 'surface', 'stroke' => 'border', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'chip')]],
    ],
    'bremo_bg_button_primary' => [
        ['android:state_pressed="true"', ['gradient' => 'brandPressed', 'radius' => $dimen('radius', 'button')]],
        ['', ['gradient' => 'brand', 'radius' => $dimen('radius', 'button')]],
    ],
    'bremo_bg_field_selector' => [
        ['android:state_focused="true"', ['fill' => 'surface', 'stroke' => 'primary600', 'strokeWidth' => $selectedBorder, 'radius' => $dimen('radius', 'field')]],
        ['', ['fill' => 'surface', 'stroke' => 'border', 'strokeWidth' => $border, 'radius' => $dimen('radius', 'field')]],
    ],
];
foreach ($selectors as $name => $items) {
    $xmlItems = [];
    foreach ($items as [$state, $spec]) {
        $xmlItems[] = '    <item'.($state === '' ? '' : ' '.$state).'>'."\n".$shapeBody($spec, '        ')."\n".'    </item>';
    }
    syncText($root, $res.'/drawable/'.$name.'.xml', implode("\n", ['<?xml version="1.0" encoding="utf-8"?>', $header, '<selector '.$android.'>', ...$xmlItems, '</selector>'])."\n", $checkOnly, $errors, $outputs);
}

// Deterministic loading arc (a static sweep, so snapshots always show the loading state).
$viewport = (float) $tokens['icon']['viewport'];
$strokeWidth = (float) $tokens['size']['progressStroke'];
$radius = ($viewport - $strokeWidth) / 2;
$centre = $viewport / 2;
$sweep = deg2rad(360 * (float) $tokens['ratio']['progressArc']);
// Start at 12 o'clock and sweep clockwise, as Compose drawArc(startAngle = -90) and SwiftUI trim do.
$endX = $centre + $radius * sin($sweep);
$endY = $centre - $radius * cos($sweep);
$largeArc = $sweep > M_PI ? 1 : 0;
$arcPath = sprintf('M%s,%s A%s,%s 0 %d,1 %s,%s', num($centre), num($centre - $radius), num($radius), num($radius), $largeArc, num(round($endX, 4)), num(round($endY, 4)));
$arc = implode("\n", [
    '<?xml version="1.0" encoding="utf-8"?>',
    $header,
    '<vector '.$android.' android:width="'.num($viewport).'dp" android:height="'.num($viewport).'dp" android:viewportWidth="'.num($viewport).'" android:viewportHeight="'.num($viewport).'">',
    '    <path android:fillColor="@android:color/transparent" android:strokeColor="'.$color('onPrimary').'" android:strokeWidth="'.num($strokeWidth).'" android:strokeLineCap="round" android:pathData="'.$arcPath.'" />',
    '</vector>',
]);
syncText($root, $res.'/drawable/bremo_progress_arc.xml', $arc."\n", $checkOnly, $errors, $outputs);

// ── Styles: TextAppearance.Bremo.*, Widget.Bremo.*, Theme.Bremo ─────────
$styles = ['<?xml version="1.0" encoding="utf-8"?>', $header, '<resources>'];
$style = static function (string $name, ?string $parent, array $items) use (&$styles): void {
    $styles[] = '    <style name="'.$name.'"'.($parent === null ? '' : ' parent="'.$parent.'"').'>';
    foreach ($items as $key => $value) {
        $styles[] = '        <item name="'.$key.'">'.$value.'</item>';
    }
    $styles[] = '    </style>';
};
$typeStyleName = static fn (string $name): string => 'TextAppearance.Bremo.'.ucfirst($name);
$style('TextAppearance.Bremo', 'TextAppearance.MaterialComponents.Body1', [
    'android:fontFamily' => $fontFor('regular'),
    'fontFamily' => $fontFor('regular'),
    'android:letterSpacing' => '0',
    'android:textAllCaps' => 'false',
]);
foreach ($tokens['type'] as $name => $value) {
    $style($typeStyleName((string) $name), 'TextAppearance.Bremo', [
        'android:textSize' => '@dimen/bremo_text_'.tokenResName((string) $name),
        'android:textColor' => $color((string) $value['color']),
        'android:fontFamily' => $fontFor((string) $value['weight']),
        'fontFamily' => $fontFor((string) $value['weight']),
    ]);
}

$style('Widget.Bremo.TextView', 'Widget.MaterialComponents.TextView', [
    'android:includeFontPadding' => 'true',
    'android:textAppearance' => '@style/'.$typeStyleName('body'),
]);
$buttonBase = [
    'android:insetTop' => '0dp',
    'android:insetBottom' => '0dp',
    'android:minWidth' => '0dp',
    'android:minHeight' => $dimen('size', 'touch_target_min'),
    'android:paddingStart' => $dimen('space', 'm'),
    'android:paddingEnd' => $dimen('space', 'm'),
    'android:paddingTop' => $dimen('space', 's'),
    'android:paddingBottom' => $dimen('space', 's'),
    'android:includeFontPadding' => 'true',
    'android:stateListAnimator' => '@null',
    'elevation' => '0dp',
    'cornerRadius' => $dimen('radius', 'button'),
    'iconPadding' => '0dp',
    'iconGravity' => 'textStart',
];
$style('Widget.Bremo.Button.Primary', 'Widget.MaterialComponents.Button.UnelevatedButton', $buttonBase + [
    'backgroundTint' => '@color/bremo_button_primary_bg',
    'android:textAppearance' => '@style/'.$typeStyleName('button'),
    'android:textColor' => $color('onPrimary'),
    'iconTint' => $color('onPrimary'),
    'rippleColor' => $color('primary50'),
]);
$style('Widget.Bremo.Button.Secondary', 'Widget.MaterialComponents.Button.OutlinedButton', $buttonBase + [
    'backgroundTint' => $color('surface'),
    'strokeColor' => $color('primary600'),
    'strokeWidth' => $border,
    'android:textAppearance' => '@style/'.$typeStyleName('button'),
    'android:textColor' => $color('primary700'),
    'iconTint' => $color('primary600'),
    'rippleColor' => $color('primary50'),
]);
$style('Widget.Bremo.Button.IconSquare', 'Widget.Bremo.Button.Secondary', [
    'android:paddingStart' => '0dp',
    'android:paddingEnd' => '0dp',
    'iconGravity' => 'textStart',
]);
$style('Widget.Bremo.Button.Text', 'Widget.MaterialComponents.Button.TextButton', $buttonBase + [
    'backgroundTint' => '@android:color/transparent',
    'android:textAppearance' => '@style/'.$typeStyleName('body'),
    'android:textColor' => $color('primary700'),
    'rippleColor' => $color('primary50'),
]);
$style('Widget.Bremo.Button.Danger', 'Widget.Bremo.Button.Text', [
    'android:textColor' => $color('danger'),
]);
$style('Widget.Bremo.Card', 'Widget.MaterialComponents.CardView', [
    'cardBackgroundColor' => $color('surface'),
    'cardCornerRadius' => $dimen('radius', 'card'),
    'cardElevation' => '0dp',
    'strokeColor' => $color('border'),
    'strokeWidth' => $border,
    'contentPadding' => $dimen('space', 'card_padding'),
    'cardPreventCornerOverlap' => 'false',
    'cardUseCompatPadding' => 'false',
]);
$style('Widget.Bremo.Card.Selectable', 'Widget.Bremo.Card', [
    'contentPadding' => $dimen('space', 'l'),
    'checkedIcon' => '@null',
    'android:checkable' => 'true',
    'cardForegroundColor' => '@android:color/transparent',
    'rippleColor' => $color('primary50'),
]);
$style('Widget.Bremo.Chip', 'Widget.MaterialComponents.Chip.Choice', [
    'chipBackgroundColor' => '@color/bremo_selectable_fill',
    'chipStrokeColor' => '@color/bremo_selectable_stroke',
    'chipStrokeWidth' => $border,
    'chipCornerRadius' => $dimen('radius', 'chip'),
    'chipMinHeight' => $dimen('size', 'chip_height'),
    'chipStartPadding' => '0dp',
    'chipEndPadding' => '0dp',
    'textStartPadding' => $dimen('space', 'm'),
    'textEndPadding' => $dimen('space', 'm'),
    'checkedIconVisible' => 'false',
    'chipIconVisible' => 'false',
    'closeIconVisible' => 'false',
    'ensureMinTouchTargetSize' => 'false',
    'rippleColor' => $color('primary50'),
    'android:textAppearance' => '@style/'.$typeStyleName('body'),
    'android:textColor' => $color('navy800'),
    'android:includeFontPadding' => 'true',
    'android:gravity' => 'center',
]);
$style('Widget.Bremo.Chip.Sort', 'Widget.Bremo.Chip', [
    'chipMinHeight' => $dimen('size', 'sort_chip_height'),
]);
$style('Widget.Bremo.EditText', 'Widget.AppCompat.EditText', [
    'android:background' => '@null',
    'android:importantForAutofill' => 'auto',
    'android:textAppearance' => '@style/'.$typeStyleName('body'),
    'android:textColor' => $color('navy800'),
    'android:textColorHint' => $color('slate300'),
    'android:includeFontPadding' => 'true',
    'android:paddingStart' => $dimen('space', 'm'),
    'android:paddingEnd' => $dimen('space', 'm'),
    'android:paddingTop' => $dimen('space', 's'),
    'android:paddingBottom' => $dimen('space', 's'),
    'android:minHeight' => $dimen('size', 'touch_target_min'),
    'android:textCursorDrawable' => '@null',
    'android:gravity' => 'center_vertical|start',
    'android:textAlignment' => 'viewStart',
]);
$style('Widget.Bremo.BottomNavigation', 'Widget.MaterialComponents.BottomNavigationView', [
    'android:background' => $color('surface'),
    'backgroundTint' => $color('surface'),
    'elevation' => '0dp',
    'itemIconTint' => '@color/bremo_nav_item',
    'itemTextColor' => '@color/bremo_nav_item',
    'itemIconSize' => $dimen('size', 'icon'),
    'itemTextAppearanceActive' => '@style/'.$typeStyleName('caption'),
    'itemTextAppearanceInactive' => '@style/'.$typeStyleName('caption'),
    'itemRippleColor' => '@android:color/transparent',
    'labelVisibilityMode' => 'labeled',
    'itemTextAppearanceActiveBoldEnabled' => 'false',
    'activeIndicatorLabelPadding' => $dimen('space', 'xs'),
    'itemHorizontalTranslationEnabled' => 'false',
]);
$style('Widget.Bremo.BottomSheet', 'Widget.MaterialComponents.BottomSheet.Modal', [
    'backgroundTint' => '@android:color/transparent',
    'android:background' => '@android:color/transparent',
    'shapeAppearance' => '@null',
]);
$style('ThemeOverlay.Bremo.BottomSheetDialog', 'ThemeOverlay.MaterialComponents.BottomSheetDialog', [
    'bottomSheetStyle' => '@style/Widget.Bremo.BottomSheet',
    'android:backgroundDimAmount' => '@dimen/bremo_opacity_scrim',
]);
$style('Theme.Bremo', 'Theme.MaterialComponents.Light.NoActionBar', [
    'colorPrimary' => $color('primary600'),
    'colorPrimaryVariant' => $color('primary700'),
    'colorOnPrimary' => $color('onPrimary'),
    'colorSecondary' => $color('primary600'),
    'colorOnSecondary' => $color('onPrimary'),
    'colorSurface' => $color('surface'),
    'colorOnSurface' => $color('navy800'),
    'colorError' => $color('danger'),
    'colorOnError' => $color('onPrimary'),
    'android:colorBackground' => $color('surface'),
    'android:windowBackground' => $color('surface'),
    'android:textColorPrimary' => $color('navy800'),
    'android:textColorSecondary' => $color('slate500'),
    'android:textColorHint' => $color('slate300'),
    'android:textViewStyle' => '@style/Widget.Bremo.TextView',
    'materialButtonStyle' => '@style/Widget.Bremo.Button.Primary',
    'materialCardViewStyle' => '@style/Widget.Bremo.Card',
    'chipStyle' => '@style/Widget.Bremo.Chip',
    'bottomNavigationStyle' => '@style/Widget.Bremo.BottomNavigation',
    // Every XML LinearLayout becomes BremoLinearLayout: RTL-safe gaps on Android 13 and older.
    'viewInflaterClass' => 'noox.bzr.design.views.BremoViewInflater',
    'bottomSheetDialogTheme' => '@style/ThemeOverlay.Bremo.BottomSheetDialog',
    'android:statusBarColor' => $color('surface'),
    'android:navigationBarColor' => $color('surface'),
    'android:windowLightStatusBar' => 'true',
]);
$styles[] = '</resources>';
syncText($root, $res.'/values/bremo_styles.xml', implode("\n", $styles)."\n", $checkOnly, $errors, $outputs);
