<?php

// Email theme (DEC-049): Arabic, RTL, colours from design/tokens.json. Included by tools/gen-design.
// Email clients do not support CSS variables, so values are written literally in this generated file.

declare(strict_types=1);

$c = static fn (string $token): string => colorHex($tokens['color'][$token]);
$t = static fn (string $type): string => num($tokens['type'][$type]['size']).'px';
$space = static fn (string $name): string => num($tokens['space'][$name]).'px';
$radius = static fn (string $name): string => num($tokens['radius'][$name]).'px';
$font = "'".$tokens['font']['family']."', Tahoma, Arial, sans-serif";

$mailCss = <<<CSS
/* Generated by tools/gen-design from design/tokens.json. Do not edit. */
body, body *:not(html):not(style):not(br):not(tr):not(code) { box-sizing: border-box; font-family: {$font}; position: relative; }
body { -webkit-text-size-adjust: none; background-color: {$c('surfaceAlt')}; color: {$c('navy800')}; height: 100%; line-height: 1.6; margin: 0; padding: 0; width: 100% !important; direction: rtl; text-align: right; }
p, ul, ol, blockquote { line-height: 1.7; text-align: right; }
a { color: {$c('primary700')}; }
a img { border: none; }
h1 { color: {$c('navy900')}; font-size: {$t('sectionTitle')}; font-weight: 700; margin-top: 0; text-align: right; }
h2 { color: {$c('navy900')}; font-size: {$t('body')}; font-weight: 700; margin-top: 0; text-align: right; }
h3 { color: {$c('navy900')}; font-size: {$t('secondary')}; font-weight: 700; margin-top: 0; text-align: right; }
p { color: {$c('navy800')}; font-size: {$t('body')}; margin-top: 0; }
p.sub { font-size: {$t('caption')}; color: {$c('slate500')}; }
img { max-width: 100%; }
.wrapper { background-color: {$c('surfaceAlt')}; margin: 0; padding: 0; width: 100%; }
.content { margin: 0; padding: 0; width: 100%; }
.header { padding: {$space('xl')} 0; text-align: center; }
.header a, .header .brand { color: {$c('primary700')}; font-size: {$t('screenTitle')}; font-weight: 700; text-decoration: none; }
.body { background-color: {$c('surfaceAlt')}; border-bottom: 1px solid {$c('surfaceAlt')}; border-top: 1px solid {$c('surfaceAlt')}; margin: 0; padding: 0; width: 100%; }
.inner-body { background-color: {$c('surface')}; border-color: {$c('border')}; border-radius: {$radius('card')}; border-width: 1px; border-style: solid; margin: 0 auto; padding: 0; width: 570px; }
.inner-body a { word-break: break-all; }
.subcopy { border-top: 1px solid {$c('border')}; margin-top: {$space('xl')}; padding-top: {$space('xl')}; }
.subcopy p { font-size: {$t('caption')}; color: {$c('slate500')}; }
.footer { margin: 0 auto; padding: 0; text-align: center; width: 570px; }
.footer p { color: {$c('slate500')}; font-size: {$t('caption')}; text-align: center; }
.footer a { color: {$c('slate500')}; text-decoration: underline; }
.table table { margin: {$space('xl')} auto; width: 100%; }
.table th { border-bottom: 1px solid {$c('border')}; margin: 0; padding-bottom: {$space('s')}; }
.table td { color: {$c('navy800')}; font-size: {$t('secondary')}; line-height: 18px; margin: 0; padding: {$space('s')} 0; }
.content-cell { max-width: 100vw; padding: {$space('xxl')}; }
.action { margin: {$space('xl')} auto; padding: 0; text-align: center; width: 100%; }
.button { border-radius: {$radius('button')}; color: {$c('onPrimary')} !important; display: inline-block; font-weight: 700; overflow: hidden; text-decoration: none; }
.button-blue, .button-primary, .button-success { background-color: {$c('primary600')}; border-bottom: 12px solid {$c('primary600')}; border-left: 24px solid {$c('primary600')}; border-right: 24px solid {$c('primary600')}; border-top: 12px solid {$c('primary600')}; }
.button-red, .button-error { background-color: {$c('danger')}; border-bottom: 12px solid {$c('danger')}; border-left: 24px solid {$c('danger')}; border-right: 24px solid {$c('danger')}; border-top: 12px solid {$c('danger')}; }
.panel { border-right: {$radius('checkbox')} solid {$c('primary600')}; margin: {$space('xl')} 0; }
.panel-content { background-color: {$c('primary50Info')}; color: {$c('primary700')}; padding: {$space('l')}; }
.panel-content p { color: {$c('primary700')}; }
.break-all { word-break: break-all; }
CSS;

syncText($root, 'resources/views/vendor/mail/html/themes/bremo.css', $mailCss."\n", $checkOnly, $errors, $outputs);

// ── Category icons (OD-08, DEC-053): flat two-tone, tones from tokens.json → categoryIcon ──
foreach (glob($root.'/design/icons/categories/*.svg') ?: [] as $categoryIcon) {
    $svg = strtr((string) file_get_contents($categoryIcon), [
        'TONE_A' => colorHex($tokens['color'][$tokens['categoryIcon']['toneA']]),
        'TONE_B' => colorHex($tokens['color'][$tokens['categoryIcon']['toneB']]),
    ]);
    syncText($root, 'public/design/categories/'.basename($categoryIcon), $svg, $checkOnly, $errors, $outputs);
}
