<?php

// Email theme (DEC-049): Arabic, RTL, colours from design/tokens.json. Included by tools/gen-design.
// Email clients do not support CSS variables, so values are written literally in this generated file.

declare(strict_types=1);

$c = static fn (string $token): string => colorHex($tokens['color'][$token]);
$t = static fn (string $type): string => num($tokens['type'][$type]['size']).'px';
$space = static fn (string $name): string => num($tokens['space'][$name]).'px';
$radius = static fn (string $name): string => num($tokens['radius'][$name]).'px';
$font = "'".$tokens['font']['family']."', Tahoma, Arial, sans-serif";

$mailCss = <<<CSS
/* Generated by tools/gen-design from design/tokens.json. Do not edit. */
body, body *:not(html):not(style):not(br):not(tr):not(code) { box-sizing: border-box; font-family: {$font}; position: relative; }
body { -webkit-text-size-adjust: none; background-color: {$c('surfaceAlt')}; color: {$c('navy800')}; height: 100%; line-height: 1.6; margin: 0; padding: 0; width: 100% !important; direction: rtl; text-align: right; }
p, ul, ol, blockquote { line-height: 1.7; text-align: right; }
a { color: {$c('primary700')}; }
a img { border: none; }
h1 { color: {$c('navy900')}; font-size: {$t('sectionTitle')}; font-weight: 700; margin-top: 0; text-align: right; }
h2 { color: {$c('navy900')}; font-size: {$t('body')}; font-weight: 700; margin-top: 0; text-align: right; }
h3 { color: {$c('navy900')}; font-size: {$t('secondary')}; font-weight: 700; margin-top: 0; text-align: right; }
p { color: {$c('navy800')}; font-size: {$t('body')}; margin-top: 0; }
p.sub { font-size: {$t('caption')}; color: {$c('slate500')}; }
img { max-width: 100%; }
.wrapper { background-color: {$c('surfaceAlt')}; margin: 0; padding: 0; width: 100%; }
.content { margin: 0; padding: 0; width: 100%; }
.header { padding: {$space('xl')} 0; text-align: center; }
.header a, .header .brand { color: {$c('primary700')}; font-size: {$t('screenTitle')}; font-weight: 700; text-decoration: none; }
.body { background-color: {$c('surfaceAlt')}; border-bottom: 1px solid {$c('surfaceAlt')}; border-top: 1px solid {$c('surfaceAlt')}; margin: 0; padding: 0; width: 100%; }
.inner-body { background-color: {$c('surface')}; border-color: {$c('border')}; border-radius: {$radius('card')}; border-width: 1px; border-style: solid; margin: 0 auto; padding: 0; width: 570px; }
.inner-body a { word-break: break-all; }
.subcopy { border-top: 1px solid {$c('border')}; margin-top: {$space('xl')}; padding-top: {$space('xl')}; }
.subcopy p { font-size: {$t('caption')}; color: {$c('slate500')}; }
.footer { margin: 0 auto; padding: 0; text-align: center; width: 570px; }
.footer p { color: {$c('slate500')}; font-size: {$t('caption')}; text-align: center; }
.footer a { color: {$c('slate500')}; text-decoration: underline; }
.table table { margin: {$space('xl')} auto; width: 100%; }
.table th { border-bottom: 1px solid {$c('border')}; margin: 0; padding-bottom: {$space('s')}; }
.table td { color: {$c('navy800')}; font-size: {$t('secondary')}; line-height: 18px; margin: 0; padding: {$space('s')} 0; }
.content-cell { max-width: 100vw; padding: {$space('xxl')}; }
.action { margin: {$space('xl')} auto; padding: 0; text-align: center; width: 100%; }
.button { border-radius: {$radius('button')}; color: {$c('onPrimary')} !important; display: inline-block; font-weight: 700; overflow: hidden; text-decoration: none; }
.button-blue, .button-primary, .button-success { background-color: {$c('primary600')}; border-bottom: 12px solid {$c('primary600')}; border-left: 24px solid {$c('primary600')}; border-right: 24px solid {$c('primary600')}; border-top: 12px solid {$c('primary600')}; }
.button-red, .button-error { background-color: {$c('danger')}; border-bottom: 12px solid {$c('danger')}; border-left: 24px solid {$c('danger')}; border-right: 24px solid {$c('danger')}; border-top: 12px solid {$c('danger')}; }
.panel { border-right: {$radius('checkbox')} solid {$c('primary600')}; margin: {$space('xl')} 0; }
.panel-content { background-color: {$c('primary50Info')}; color: {$c('primary700')}; padding: {$space('l')}; }
.panel-content p { color: {$c('primary700')}; }
.break-all { word-break: break-all; }
CSS;

syncText($root, 'resources/views/vendor/mail/html/themes/bremo.css', $mailCss."\n", $checkOnly, $errors, $outputs);

$categoryKeys = [];
// ── Category icons (OD-08, DEC-053): flat two-tone, tones from tokens.json → categoryIcon ──
// DEC-063: each category has its own hue — TONE_A is a top-start → bottom-end gradient, TONE_B its light tint.
$categoryPalettes = [];
foreach (glob($root.'/design/icons/categories/*.svg') ?: [] as $categoryIcon) {
    $paletteKey = pathinfo($categoryIcon, PATHINFO_FILENAME);
    $palette = $tokens['categoryIcon']['palette'][$paletteKey] ?? throw new RuntimeException("No palette for category icon {$paletteKey}");
    $categoryPalettes[$paletteKey] = $palette;
    $template = (string) file_get_contents($categoryIcon);
    preg_match('/viewBox="0 0 (\d+) (\d+)"/', $template, $viewBox);
    $defs = '<defs><linearGradient id="tone-a" x1="0" y1="0" x2="'.$viewBox[1].'" y2="'.$viewBox[2].'" gradientUnits="userSpaceOnUse">'
        .'<stop offset="0" stop-color="'.$palette['from'].'"/><stop offset="1" stop-color="'.$palette['to'].'"/></linearGradient></defs>';
    $svg = (string) preg_replace('/(<svg\b[^>]*>)/', '$1'."\n  ".$defs, strtr($template, [
        'TONE_A' => 'url(#tone-a)',
        // A mid shade of the hue, so the second tone still reads on the tinted well.
        'TONE_B' => mixWithWhite($palette['from'], 0.55),
    ]), 1);
    syncText($root, 'public/design/categories/'.basename($categoryIcon), $svg, $checkOnly, $errors, $outputs);

    // DEC-059 — the same two-tone icons bundled in both apps, keyed by the file name the server sends in icon_path.
    $key = pathinfo($categoryIcon, PATHINFO_FILENAME);
    $assetName = 'category_'.str_replace('-', '_', $key);
    $categoryKeys[$key] = $assetName;
    syncText($root, 'androidapp/core/design/src/main/res/drawable/bremo_'.$assetName.'.xml', categoryVector($svg, $palette), $checkOnly, $errors, $outputs);
    $imageset = 'iosapp/Packages/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/'.$assetName.'.imageset';
    $contents = [
        'images' => [['filename' => $key.'.svg', 'idiom' => 'universal']],
        'info' => ['author' => 'tools/gen-design', 'version' => 1],
        'properties' => ['preserves-vector-representation' => true, 'template-rendering-intent' => 'original'],
    ];
    syncText($root, $imageset.'/Contents.json', (string) json_encode($contents, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)."\n", $checkOnly, $errors, $outputs);
    syncText($root, $imageset.'/'.$key.'.svg', $svg, $checkOnly, $errors, $outputs);
}
ksort($categoryKeys);
$kotlinCases = implode("\n", array_map(
    static fn (string $key, string $asset): string => "        \"{$key}\" -> R.drawable.bremo_{$asset}",
    array_keys($categoryKeys), $categoryKeys,
));
ksort($categoryPalettes);
$kotlinArgb = static fn (string $hex): string => '0x'.strtoupper(strlen(ltrim($hex, '#')) === 8 ? ltrim($hex, '#') : 'FF'.ltrim($hex, '#')).'.toInt()';
$kotlinPalettes = implode("\n", array_map(
    static fn (string $key, array $palette): string => "        \"{$key}\" -> CategoryPalette({$kotlinArgb($palette['from'])}, {$kotlinArgb($palette['to'])}, {$kotlinArgb($palette['tint'])})",
    array_keys($categoryPalettes), $categoryPalettes,
));
$brandPalette = 'CategoryPalette('.$kotlinArgb($tokens['gradient']['iconBrand']['from']).', '.$kotlinArgb($tokens['gradient']['iconBrand']['to']).', '.$kotlinArgb(colorHex($tokens['color']['primary50'])).')';
syncText($root, 'androidapp/core/design/src/main/kotlin/noox/bzr/design/generated/CategoryIcons.kt', <<<KOTLIN
// Generated by tools/gen-design. Do not edit.
package noox.bzr.design.generated

import androidx.annotation.DrawableRes
import noox.bzr.design.R

/** DEC-059: two-tone category icons keyed by the `icon_path` file name from `/catalog`; unknown keys fall back. */
object CategoryIcons {
    @DrawableRes
    fun drawable(key: String): Int = when (key) {
{$kotlinCases}
        else -> R.drawable.ic_home
    }

    /** DEC-063: the category's gradient and tint; unknown keys use the brand gradient. */
    fun palette(key: String?): CategoryPalette = when (key) {
{$kotlinPalettes}
        else -> {$brandPalette}
    }
}

/** ARGB colours of one category: icon gradient [from] → [to], and the [tint] of its well. */
data class CategoryPalette(val from: Int, val to: Int, val tint: Int)

KOTLIN, $checkOnly, $errors, $outputs);
$swiftCases = implode("\n", array_map(
    static fn (string $key, string $asset): string => "        \"{$key}\": \"{$asset}\",",
    array_keys($categoryKeys), $categoryKeys,
));
syncText($root, 'iosapp/Packages/DesignSystem/Sources/DesignSystem/Generated/CategoryIcons.swift', <<<SWIFT
// Generated by tools/gen-design. Do not edit.

/// DEC-059: two-tone category icons keyed by the `icon_path` file name from `/catalog`.
public enum CategoryIcons {
    static let assets: [String: String] = [
{$swiftCases}
    ]

    /// The bundled asset for a key, or nil so the caller falls back to a generic icon.
    public static func asset(_ key: String) -> String? { assets[key] }
}

SWIFT, $checkOnly, $errors, $outputs);

/** Two-tone category SVG (rect, circle, path; fills and one round stroke) to an Android vector drawable. */
/** The colour moved toward white by $amount (0 = unchanged, 1 = white). */
function mixWithWhite(string $hex, float $amount): string
{
    $raw = ltrim($hex, '#');
    $channels = array_map(static fn (string $part): int => (int) round(hexdec($part) + (255 - hexdec($part)) * $amount), str_split($raw, 2));

    return '#'.strtoupper(implode('', array_map(static fn (int $value): string => str_pad(dechex($value), 2, '0', STR_PAD_LEFT), $channels)));
}

/** @param array{from: string, to: string, tint: string} $palette */
function categoryVector(string $svg, array $palette): string
{
    preg_match('/viewBox="0 0 (\d+) (\d+)"/', $svg, $box);
    $paths = [];
    preg_match_all('/<(rect|circle|path)\b([^>]*)\/>/', $svg, $elements, PREG_SET_ORDER);
    foreach ($elements as [, $tag, $attributes]) {
        preg_match_all('/([a-z-]+)="([^"]*)"/', $attributes, $pairs, PREG_SET_ORDER);
        $a = [];
        foreach ($pairs as [, $name, $value]) {
            $a[$name] = $value;
        }
        $data = match ($tag) {
            'rect' => rectPath((float) $a['x'], (float) $a['y'], (float) $a['width'], (float) $a['height'], (float) ($a['rx'] ?? 0)),
            'circle' => circlePath((float) $a['cx'], (float) $a['cy'], (float) $a['r']),
            'path' => $a['d'],
        };
        $paintAttribute = isset($a['stroke']) ? 'strokeColor' : 'fillColor';
        $paintValue = $a['stroke'] ?? $a['fill'];
        $strokeExtras = isset($a['stroke'])
            ? ' android:strokeWidth="'.$a['stroke-width'].'" android:strokeLineCap="'.($a['stroke-linecap'] ?? 'butt').'"'
            : '';
        $pathData = 'android:pathData="'.htmlspecialchars($data, ENT_XML1).'"';
        if ($paintValue === 'url(#tone-a)') {
            // DEC-063: the category gradient, top-start → bottom-end over the whole viewport.
            $paths[] = '    <path '.$pathData.$strokeExtras.'>'."\n"
                .'        <aapt:attr name="android:'.$paintAttribute.'">'."\n"
                .'            <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="'.$box[1].'" android:endY="'.$box[2].'" android:startColor="'.$palette['from'].'" android:endColor="'.$palette['to'].'"/>'."\n"
                .'        </aapt:attr>'."\n"
                .'    </path>';
        } else {
            $paths[] = '    <path android:'.$paintAttribute.'="'.$paintValue.'"'.$strokeExtras.' '.$pathData.'/>';
        }
    }

    return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        ."<!-- Generated by tools/gen-design from design/icons/categories. Do not edit. -->\n"
        ."<vector xmlns:android=\"http://schemas.android.com/apk/res/android\" xmlns:aapt=\"http://schemas.android.com/aapt\" android:width=\"{$box[1]}dp\" android:height=\"{$box[2]}dp\" android:viewportWidth=\"{$box[1]}\" android:viewportHeight=\"{$box[2]}\">\n"
        .implode("\n", $paths)."\n</vector>\n";
}

function rectPath(float $x, float $y, float $w, float $h, float $r): string
{
    $n = static fn (float $v): string => rtrim(rtrim(number_format($v, 3, '.', ''), '0'), '.');
    $r = min($r, $w / 2, $h / 2);
    if ($r <= 0) {
        return "M{$n($x)},{$n($y)}h{$n($w)}v{$n($h)}h{$n(-$w)}z";
    }

    return "M{$n($x + $r)},{$n($y)}h{$n($w - 2 * $r)}a{$n($r)},{$n($r)} 0 0 1 {$n($r)},{$n($r)}"
        ."v{$n($h - 2 * $r)}a{$n($r)},{$n($r)} 0 0 1 {$n(-$r)},{$n($r)}"
        ."h{$n(-($w - 2 * $r))}a{$n($r)},{$n($r)} 0 0 1 {$n(-$r)},{$n(-$r)}"
        ."v{$n(-($h - 2 * $r))}a{$n($r)},{$n($r)} 0 0 1 {$n($r)},{$n(-$r)}z";
}

function circlePath(float $cx, float $cy, float $r): string
{
    $n = static fn (float $v): string => rtrim(rtrim(number_format($v, 3, '.', ''), '0'), '.');

    return "M{$n($cx - $r)},{$n($cy)}a{$n($r)},{$n($r)} 0 1 0 {$n(2 * $r)},0a{$n($r)},{$n($r)} 0 1 0 {$n(-2 * $r)},0z";
}
