<?php

// Email theme (DEC-049): Arabic, RTL, colours from design/tokens.json. Included by tools/gen-design.
// Email clients do not support CSS variables, so values are written literally in this generated file.

declare(strict_types=1);

$c = static fn (string $token): string => colorHex($tokens['color'][$token]);
$t = static fn (string $type): string => num($tokens['type'][$type]['size']).'px';
$space = static fn (string $name): string => num($tokens['space'][$name]).'px';
$radius = static fn (string $name): string => num($tokens['radius'][$name]).'px';
$font = "'".$tokens['font']['family']."', Tahoma, Arial, sans-serif";

$mailCss = <<<CSS
/* Generated by tools/gen-design from design/tokens.json. Do not edit. */
body, body *:not(html):not(style):not(br):not(tr):not(code) { box-sizing: border-box; font-family: {$font}; position: relative; }
body { -webkit-text-size-adjust: none; background-color: {$c('surfaceAlt')}; color: {$c('navy800')}; height: 100%; line-height: 1.6; margin: 0; padding: 0; width: 100% !important; direction: rtl; text-align: right; }
p, ul, ol, blockquote { line-height: 1.7; text-align: right; }
a { color: {$c('primary700')}; }
a img { border: none; }
h1 { color: {$c('navy900')}; font-size: {$t('sectionTitle')}; font-weight: 700; margin-top: 0; text-align: right; }
h2 { color: {$c('navy900')}; font-size: {$t('body')}; font-weight: 700; margin-top: 0; text-align: right; }
h3 { color: {$c('navy900')}; font-size: {$t('secondary')}; font-weight: 700; margin-top: 0; text-align: right; }
p { color: {$c('navy800')}; font-size: {$t('body')}; margin-top: 0; }
p.sub { font-size: {$t('caption')}; color: {$c('slate500')}; }
img { max-width: 100%; }
.wrapper { background-color: {$c('surfaceAlt')}; margin: 0; padding: 0; width: 100%; }
.content { margin: 0; padding: 0; width: 100%; }
.header { padding: {$space('xl')} 0; text-align: center; }
.header a, .header .brand { color: {$c('primary700')}; font-size: {$t('screenTitle')}; font-weight: 700; text-decoration: none; }
.body { background-color: {$c('surfaceAlt')}; border-bottom: 1px solid {$c('surfaceAlt')}; border-top: 1px solid {$c('surfaceAlt')}; margin: 0; padding: 0; width: 100%; }
.inner-body { background-color: {$c('surface')}; border-color: {$c('border')}; border-radius: {$radius('card')}; border-width: 1px; border-style: solid; margin: 0 auto; padding: 0; width: 570px; }
.inner-body a { word-break: break-all; }
.subcopy { border-top: 1px solid {$c('border')}; margin-top: {$space('xl')}; padding-top: {$space('xl')}; }
.subcopy p { font-size: {$t('caption')}; color: {$c('slate500')}; }
.footer { margin: 0 auto; padding: 0; text-align: center; width: 570px; }
.footer p { color: {$c('slate500')}; font-size: {$t('caption')}; text-align: center; }
.footer a { color: {$c('slate500')}; text-decoration: underline; }
.table table { margin: {$space('xl')} auto; width: 100%; }
.table th { border-bottom: 1px solid {$c('border')}; margin: 0; padding-bottom: {$space('s')}; }
.table td { color: {$c('navy800')}; font-size: {$t('secondary')}; line-height: 18px; margin: 0; padding: {$space('s')} 0; }
.content-cell { max-width: 100vw; padding: {$space('xxl')}; }
.action { margin: {$space('xl')} auto; padding: 0; text-align: center; width: 100%; }
.button { border-radius: {$radius('button')}; color: {$c('onPrimary')} !important; display: inline-block; font-weight: 700; overflow: hidden; text-decoration: none; }
.button-blue, .button-primary, .button-success { background-color: {$c('primary600')}; border-bottom: 12px solid {$c('primary600')}; border-left: 24px solid {$c('primary600')}; border-right: 24px solid {$c('primary600')}; border-top: 12px solid {$c('primary600')}; }
.button-red, .button-error { background-color: {$c('danger')}; border-bottom: 12px solid {$c('danger')}; border-left: 24px solid {$c('danger')}; border-right: 24px solid {$c('danger')}; border-top: 12px solid {$c('danger')}; }
.panel { border-right: {$radius('checkbox')} solid {$c('primary600')}; margin: {$space('xl')} 0; }
.panel-content { background-color: {$c('primary50Info')}; color: {$c('primary700')}; padding: {$space('l')}; }
.panel-content p { color: {$c('primary700')}; }
.break-all { word-break: break-all; }
CSS;

syncText($root, 'resources/views/vendor/mail/html/themes/bremo.css', $mailCss."\n", $checkOnly, $errors, $outputs);

$categoryKeys = [];
// ── Category icons (OD-08, DEC-053): flat two-tone, tones from tokens.json → categoryIcon ──
foreach (glob($root.'/design/icons/categories/*.svg') ?: [] as $categoryIcon) {
    $svg = strtr((string) file_get_contents($categoryIcon), [
        'TONE_A' => colorHex($tokens['color'][$tokens['categoryIcon']['toneA']]),
        'TONE_B' => colorHex($tokens['color'][$tokens['categoryIcon']['toneB']]),
    ]);
    syncText($root, 'public/design/categories/'.basename($categoryIcon), $svg, $checkOnly, $errors, $outputs);

    // DEC-059 — the same two-tone icons bundled in both apps, keyed by the file name the server sends in icon_path.
    $key = pathinfo($categoryIcon, PATHINFO_FILENAME);
    $assetName = 'category_'.str_replace('-', '_', $key);
    $categoryKeys[$key] = $assetName;
    syncText($root, 'androidapp/core/design/src/main/res/drawable/bremo_'.$assetName.'.xml', categoryVector($svg), $checkOnly, $errors, $outputs);
    $imageset = 'iosapp/Packages/DesignSystem/Sources/DesignSystem/Resources/Assets.xcassets/'.$assetName.'.imageset';
    $contents = [
        'images' => [['filename' => $key.'.svg', 'idiom' => 'universal']],
        'info' => ['author' => 'tools/gen-design', 'version' => 1],
        'properties' => ['preserves-vector-representation' => true, 'template-rendering-intent' => 'original'],
    ];
    syncText($root, $imageset.'/Contents.json', (string) json_encode($contents, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES)."\n", $checkOnly, $errors, $outputs);
    syncText($root, $imageset.'/'.$key.'.svg', $svg, $checkOnly, $errors, $outputs);
}
ksort($categoryKeys);
$kotlinCases = implode("\n", array_map(
    static fn (string $key, string $asset): string => "        \"{$key}\" -> R.drawable.bremo_{$asset}",
    array_keys($categoryKeys), $categoryKeys,
));
syncText($root, 'androidapp/core/design/src/main/kotlin/noox/bzr/design/generated/CategoryIcons.kt', <<<KOTLIN
// Generated by tools/gen-design. Do not edit.
package noox.bzr.design.generated

import androidx.annotation.DrawableRes
import noox.bzr.design.R

/** DEC-059: two-tone category icons keyed by the `icon_path` file name from `/catalog`; unknown keys fall back. */
object CategoryIcons {
    @DrawableRes
    fun drawable(key: String): Int = when (key) {
{$kotlinCases}
        else -> R.drawable.ic_home
    }
}

KOTLIN, $checkOnly, $errors, $outputs);
$swiftCases = implode("\n", array_map(
    static fn (string $key, string $asset): string => "        \"{$key}\": \"{$asset}\",",
    array_keys($categoryKeys), $categoryKeys,
));
syncText($root, 'iosapp/Packages/DesignSystem/Sources/DesignSystem/Generated/CategoryIcons.swift', <<<SWIFT
// Generated by tools/gen-design. Do not edit.

/// DEC-059: two-tone category icons keyed by the `icon_path` file name from `/catalog`.
public enum CategoryIcons {
    static let assets: [String: String] = [
{$swiftCases}
    ]

    /// The bundled asset for a key, or nil so the caller falls back to a generic icon.
    public static func asset(_ key: String) -> String? { assets[key] }
}

SWIFT, $checkOnly, $errors, $outputs);

/** Two-tone category SVG (rect, circle, path; fills and one round stroke) to an Android vector drawable. */
function categoryVector(string $svg): string
{
    preg_match('/viewBox="0 0 (\d+) (\d+)"/', $svg, $box);
    $paths = [];
    preg_match_all('/<(rect|circle|path)\b([^>]*)\/>/', $svg, $elements, PREG_SET_ORDER);
    foreach ($elements as [, $tag, $attributes]) {
        preg_match_all('/([a-z-]+)="([^"]*)"/', $attributes, $pairs, PREG_SET_ORDER);
        $a = [];
        foreach ($pairs as [, $name, $value]) {
            $a[$name] = $value;
        }
        $data = match ($tag) {
            'rect' => rectPath((float) $a['x'], (float) $a['y'], (float) $a['width'], (float) $a['height'], (float) ($a['rx'] ?? 0)),
            'circle' => circlePath((float) $a['cx'], (float) $a['cy'], (float) $a['r']),
            'path' => $a['d'],
        };
        $paint = isset($a['stroke'])
            ? 'android:strokeColor="'.$a['stroke'].'" android:strokeWidth="'.$a['stroke-width'].'" android:strokeLineCap="'.($a['stroke-linecap'] ?? 'butt').'"'
            : 'android:fillColor="'.$a['fill'].'"';
        $paths[] = '    <path '.$paint.' android:pathData="'.htmlspecialchars($data, ENT_XML1).'"/>';
    }

    return "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
        ."<!-- Generated by tools/gen-design from design/icons/categories. Do not edit. -->\n"
        ."<vector xmlns:android=\"http://schemas.android.com/apk/res/android\" android:width=\"{$box[1]}dp\" android:height=\"{$box[2]}dp\" android:viewportWidth=\"{$box[1]}\" android:viewportHeight=\"{$box[2]}\">\n"
        .implode("\n", $paths)."\n</vector>\n";
}

function rectPath(float $x, float $y, float $w, float $h, float $r): string
{
    $n = static fn (float $v): string => rtrim(rtrim(number_format($v, 3, '.', ''), '0'), '.');
    $r = min($r, $w / 2, $h / 2);
    if ($r <= 0) {
        return "M{$n($x)},{$n($y)}h{$n($w)}v{$n($h)}h{$n(-$w)}z";
    }

    return "M{$n($x + $r)},{$n($y)}h{$n($w - 2 * $r)}a{$n($r)},{$n($r)} 0 0 1 {$n($r)},{$n($r)}"
        ."v{$n($h - 2 * $r)}a{$n($r)},{$n($r)} 0 0 1 {$n(-$r)},{$n($r)}"
        ."h{$n(-($w - 2 * $r))}a{$n($r)},{$n($r)} 0 0 1 {$n(-$r)},{$n(-$r)}"
        ."v{$n(-($h - 2 * $r))}a{$n($r)},{$n($r)} 0 0 1 {$n($r)},{$n(-$r)}z";
}

function circlePath(float $cx, float $cy, float $r): string
{
    $n = static fn (float $v): string => rtrim(rtrim(number_format($v, 3, '.', ''), '0'), '.');

    return "M{$n($cx - $r)},{$n($cy)}a{$n($r)},{$n($r)} 0 1 0 {$n(2 * $r)},0a{$n($r)},{$n($r)} 0 1 0 {$n(-2 * $r)},0z";
}
